# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "lucide-react"
      - dependency-name: "@types/node"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
      shadcn:
        patterns:
          - "@radix-ui/*"
          - "class-variance-authority"
          - "clsx"
      tailwind:
        patterns:
          - "tailwind*"
          - "postcss"
          - "autoprefixer"
          - "@tailwindcss/*"
      tanstack:
        patterns:
          - "@tanstack/*"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
