name: release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install -g yarn
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ethui'

      - run: yarn install --frozen-lockfile

      - run: yarn version prerelease
      - run: yarn npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push version changes to main branch 📤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json
