name: test

on:
  push:
    branches:
      - test
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.ETHUI_DEPLOYER_APP_ID }}
          private-key: ${{ secrets.ETHUI_DEPLOYER_PKEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - run: echo -e "\n" >> package.json

      - id: version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Push version changes to main branch 📤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ethui-deployer
          commit_user_email: dev@ethui.dev
          commit_author: ethui-deployer <dev@ethui.dev>
          commit_message: "release ${{ steps.version.outputs.version }}\n[skip ci]"
          branch: test
          file_pattern: package.json
